/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Reflection = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Template = IDL.Record({
  'id' : IDL.Nat,
  'previewImage' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'hashtags' : IDL.Vec(IDL.Text),
  'postTimestamp' : Time,
  'template' : Template,
  'reflection' : Reflection,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generatePoster' : IDL.Func([Reflection, IDL.Nat, IDL.Vec(IDL.Text)], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFilteredReflections' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Reflection)],
      ['query'],
    ),
  'getLastReflections' : IDL.Func([IDL.Nat], [IDL.Vec(Reflection)], ['query']),
  'getPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getPortfolioByHashtag' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getReflection' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
  'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveReflection' : IDL.Func([Reflection], [], []),
  'updateReflection' : IDL.Func([Reflection], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Reflection = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Template = IDL.Record({
    'id' : IDL.Nat,
    'previewImage' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'hashtags' : IDL.Vec(IDL.Text),
    'postTimestamp' : Time,
    'template' : Template,
    'reflection' : Reflection,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generatePoster' : IDL.Func(
        [Reflection, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFilteredReflections' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Reflection)],
        ['query'],
      ),
    'getLastReflections' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Reflection)],
        ['query'],
      ),
    'getPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getPortfolioByHashtag' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getReflection' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
    'getTemplates' : IDL.Func([], [IDL.Vec(Template)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveReflection' : IDL.Func([Reflection], [], []),
    'updateReflection' : IDL.Func([Reflection], [], []),
  });
};

export const init = ({ IDL }) => { return []; };