/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PortfolioItem {
  'hashtags' : Array<string>,
  'postTimestamp' : Time,
  'template' : Template,
  'reflection' : Reflection,
}
export interface Reflection {
  'title' : string,
  'body' : string,
  'timestamp' : Time,
}
export interface Template {
  'id' : bigint,
  'previewImage' : string,
  'name' : string,
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generatePoster' : ActorMethod<
    [Reflection, bigint, Array<string>],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFilteredReflections' : ActorMethod<[string], Array<Reflection>>,
  'getLastReflections' : ActorMethod<[bigint], Array<Reflection>>,
  'getPortfolio' : ActorMethod<[], Array<PortfolioItem>>,
  'getPortfolioByHashtag' : ActorMethod<[string], Array<PortfolioItem>>,
  'getReflection' : ActorMethod<[], Array<Reflection>>,
  'getTemplates' : ActorMethod<[], Array<Template>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveReflection' : ActorMethod<[Reflection], undefined>,
  'updateReflection' : ActorMethod<[Reflection], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];